### ISSUE TITLE
racket cs download is broken

### ISSUE THREAD

**Issue by pmatos** [greghendershott/travis-racket#30]
There's no such file in `UTAH_BASE` with the filename `racket-current-x86_64-linux-cs-xenial.sh`.

**Comment by greghendershott** [comment]
This was very recently added in #28 by @LiberalArtist. Maybe we're pointing the right place, but the CS snapshot is not necessarily as highly-available yet as the non-CS snapshot?

**Comment by LiberalArtist** [comment]
I just saw this broke in [one of my builds](https://travis-ci.org/LiberalArtist/adjutor/jobs/460625399) as well, whereas it had worked for me in previous builds. I think it is because last night's Utah Racket-on-Chez build [failed](https://www.cs.utah.edu/plt/snapshots/).

**Comment by greghendershott** [comment]
Even plain `HEAD` will break, although rarely (and more likely due to university hosting infrastructure than the project itself, AFAICT.)

In most of my projects' `.travis.yml` I add `HEAD` and now `HEADCS` under `allow_failures`. I also enable `fast_finish`.

```yml

# You may want to test against certain versions of Racket, without
# having them count against the overall success/failure.
matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE
  # Fast finish: Overall build result is determined as soon as any of
  # its rows have failed, or, all of its rows that aren't allowed to
  # fail have succeeded.
  fast_finish: true
```
